# Generated by Django 3.2 on 2021-04-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testuser',
            table='test_user',
        ),
    ]
